apiVersion: v1
kind: Pod
metadata:
  name: housing-batch-pod
spec:
  containers:
  - name: housing-app
    image: 435141881759.dkr.ecr.ap-southeast-1.amazonaws.com/housing-predictor:latest
    imagePullPolicy: Always
    command: ["python", "-m", "scripts.main"]
    workingDir: /app        
  restartPolicy: Never
