name: CI Pipeline

on:
  push:
    branches: [ "assg1" ]
  pull_request:
    branches: [ "main" ]

jobs:
  style-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Miniforge3
        miniforge-version: latest
        use-mamba: false
        activate-environment: housing_predictor
        environment-file: env.yml
        python-version: "3.8"
    - name: Install tree
      run: sudo apt-get install tree
    - name: Run black
      shell: bash -l {0}
      run: black --check .
    - name: Run isort
      shell: bash -l {0}
      run: isort --check .
    - name: Run flake8
      shell: bash -l {0}
      run: flake8 .

  unit-test:
    needs: style-test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Miniforge3
        miniforge-version: latest
        use-mamba: true
        activate-environment: housing_predictor
        environment-file: env.yml
        python-version: "3.8"
    - name: Install package in dev mode
      run: pip install -e .
    - name: Run pytest
      shell: bash -l {0}
      run: pytest -v --cov=src/housing_predictor

  build:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Miniforge3
        miniforge-version: latest
        use-mamba: true
        activate-environment: housing_predictor
        environment-file: env.yml
        python-version: "3.8"
    - name: Install tree
      run: sudo apt-get install tree
    - name: Show directory tree before build
      run: tree
    - name: Build package
      run: python setup.py sdist bdist_wheel
    - name: Show directory tree after build
      run: tree
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          dist/*
          env.yml

  install:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: dist/
    - name: Set up Miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Miniforge3
        miniforge-version: latest
        use-mamba: true
        activate-environment: housing_predictor
        environment-file: env.yml
        python-version: "3.8"
    - name: Install package
      run: pip install $(find dist -name "*.whl")
    - name: Install mlflow
      run: pip install mlflow

    - name: Run scripts with logging
      run: |
        python -m scripts.main
        # python scripts/ingest_data.py --output-path data/processed --log-level DEBUG
        # python scripts/train.py --input-path data/processed/housing_train.csv --output-path models --log-level DEBUG
        # python scripts/score.py --model-path models/housing_model.pkl --data-path data/processed/housing_test.csv --output-path results --log-level DEBUG

  drift-test:
    needs: install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install evidently
      run: pip install evidently

    - name: Run drift monitoring
      working-directory: deploy
      run: python monitor.py

    - name: Show drift status
      run: cat data/monitoring/drift_status.txt
