jobs:
  style-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 pytest
    - name: Run black
      run: black --check .
    # ... rest of the style-test job remains same ...

  unit-test:
    needs: style-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
    - name: Run pytest
      run: pytest -v --cov=housing_predictor

  build:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools
    - name: Show directory tree before build
      run: tree
    - name: Build package
      run: python setup.py sdist bdist_wheel
    - name: Show directory tree after build
      run: tree
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          dist/*
          env.yml

  install:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
        path: dist/
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Install package
      run: pip install dist/*.whl
    - name: Run scripts with logging
      run: |
        python scripts/ingest_data.py --output-path data/processed --log-level DEBUG
        python scripts/train.py --input-path data/processed/housing_train.csv --output-path models --log-level DEBUG
        python scripts/score.py --model-path models/housing_model.pkl --data-path data/processed/housing_test.csv --output-path results --log-level DEBUG